---
- name: Configurar hosts
  hosts: all
  become: true

  tasks:
    - name: Add nodes to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
        create: yes
        state: present
      loop: "{{ groups['servers'] }}"

    - name: Add nodees to /etc/cloud/templates/hosts.debian.tmpl
      lineinfile:
        path: /etc/cloud/templates/hosts.debian.tmpl
        line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
        create: yes
        state: present
      loop: "{{ groups['servers'] }}"
