- name: Fetch and distribute SSH key for Ceph
  hosts: all
  become: yes
  tasks:
    - name: Generar par de llaves SSH para root si no existe
      openssh_keypair:
        path: /root/.ssh/id_rsa
        type: rsa
        owner: root
        group: root
        mode: '0600'
        comment: "root@{{ inventory_hostname }}"
        state: present    

    - name: Fetch the public SSH key from nodo1
      ansible.builtin.fetch:
        src: /root/.ssh/id_rsa.pub
        dest: ./id_rsa.pub
        flat: yes
      delegate_to: nodo1
      run_once: true

    - name: Add public SSH key to authorized_keys on each node
      ansible.builtin.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', './id_rsa.pub') }}"

    - name: Add SSH fingerprints to known_hosts
      ansible.builtin.known_hosts:
        path: /root/.ssh/known_hosts
        name: "{{ item }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -H ' + item) }}"
      with_items:
        - 192.168.122.101  # nodo1
        - 192.168.122.102  # nodo2
        - 192.168.122.103  # nodo3

    - name: Check SSH connection to each node
      ansible.builtin.shell: |
        ssh -o StrictHostKeyChecking=no \
            -o ConnectTimeout=5 \
            -o BatchMode=yes \
            root@{{ item }} "echo OK"
      delegate_to: nodo1
      register: ssh_check
      ignore_errors: yes
      changed_when: false
      with_items:
        - nodo1
        - nodo2
        - nodo3

    - name: Show results
      ansible.builtin.debug:
        var: ssh_check.results

