- hosts: all
  become: yes
  tasks:
    - name: Actualizar los paquetes de APT
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - python3
          - lvm2
          - docker
          - docker.io
          - chrony
        state: present

    - name: Download cephadm using get_url
      ansible.builtin.get_url:
        url: https://github.com/ceph/ceph/raw/quincy/src/cephadm/cephadm
        dest: /usr/local/bin/cephadm
        mode: '0755'

    - name: Add Ceph repository
      ansible.builtin.command:
        cmd: "/usr/local/bin/cephadm add-repo --release reef"
        creates: /etc/apt/sources.list.d/ceph.list

    - name: Bootstrap Ceph on the main node
      ansible.builtin.command:
        cmd: "/usr/local/bin/cephadm bootstrap --mon-ip {{ ansible_host }}"
      when: inventory_hostname == 'nodo1'
      run_once: true

    - name: Install ceph-common 
      apt:
        name:
          - ceph-common
        state: present

    - name: Fetch /etc/ceph/ceph.pub to local directory
      ansible.builtin.fetch:
        src: /etc/ceph/ceph.pub
        dest: ./ceph.pub
        flat: yes
      delegate_to: nodo1
      run_once: true

    - name: Add Ceph public key to authorized_keys
      ansible.builtin.lineinfile:
        path: /root/.ssh/authorized_keys
        line: "{{ lookup('file', './ceph.pub') }}"
        state: present
      become: yes
      when: inventory_hostname != 'nodo1'

    - name: Add other nodes to Ceph Orchestrator
      ansible.builtin.shell: |
        ceph orch host add {{ inventory_hostname }} {{ ansible_host }} --labels _admin
      args:
        executable: /bin/bash
      delegate_to: nodo1
      when: inventory_hostname != 'nodo1'

    - name: Add OSDs to each node
      ansible.builtin.shell: |
        ceph orch daemon add osd {{ inventory_hostname }}:/dev/vdb
        ceph orch daemon add osd {{ inventory_hostname }}:/dev/vdc
      args:
        executable: /bin/bash
      delegate_to: nodo1
